### ISSUE TITLE
Update SDK to be compliant with spec v0.2.0

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/golang-sdk#36]
Update the SDK to be compliant with the v0.2.0 spec.

## Flag Evaluation API
- [x]  [#116](https://github.com/open-feature/spec/pull/116) - Have different methods for float and int

## Providers
- [x] #38

## Evaluation Context
- [x] #40
- [x]  [#120](https://github.com/open-feature/spec/pull/120) - Add the ability to fetch all custom fields
- [x]  [#121](https://github.com/open-feature/spec/pull/121) - Ensure evaluation context keys are unique

## Hooks
- [x]  [#119](https://github.com/open-feature/spec/pull/119) - Ensure provider hook are correctly ordered

**Full Changelog**: https://github.com/open-feature/spec/compare/v0.1.0...v0.2.0

**Comment by skyerus** [comment]
> https://github.com/open-feature/spec/pull/116 - Have different methods for float and int

Was handled in https://github.com/open-feature/golang-sdk/issues/34

**Comment by skyerus** [comment]
I don't think we need to make any changes in the golang-sdk to achieve https://github.com/open-feature/spec/pull/120 , we can directly access the map to retrieve a custom field by key. We can also simply loop through the map to retrieve all key/value pairs.

**Comment by skyerus** [comment]
https://github.com/open-feature/spec/pull/121 was created with the java implementation in mind where each type is stored in a structure of its own which meant it was possible to have key collisions. In the golang-sdk we store each attribute in the same map, no matter the type so collisions aren't possible.

**Comment by skyerus** [comment]
> https://github.com/open-feature/spec/pull/119 - Ensure provider hook are correctly ordered

Handled in https://github.com/open-feature/golang-sdk/issues/38
